name: Run Azure Login With a Service Principal Secret

on:
  push:
    branches: [ "actiontest" ]
  pull_request:
    branches: [ "actiontest" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: hello-action
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          echo hello

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        auth-type: SERVICE_PRINCIPAL

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
